services:
  mongodb:
    image: mongo:noble
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
    volumes:
      - ./mongodb_data:/data/db
    restart: unless-stopped
